// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSHMm9bd8YZgUqumr60JEr6g8b507dSo',
    appId: '1:224513566383:web:18ff23ec350ee7b926965a',
    messagingSenderId: '224513566383',
    projectId: 'shopingmall-flutter-6ce8c',
    authDomain: 'shopingmall-flutter-6ce8c.firebaseapp.com',
    storageBucket: 'shopingmall-flutter-6ce8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcPFdCGS68qgcw3Xhx83LGCpvYUaRvEIQ',
    appId: '1:224513566383:android:31e33acc57f2964d26965a',
    messagingSenderId: '224513566383',
    projectId: 'shopingmall-flutter-6ce8c',
    storageBucket: 'shopingmall-flutter-6ce8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3GpnMgu7YfRD9ybPd8Bh6sU-bJyOXmD8',
    appId: '1:224513566383:ios:bd6206ae48646f5926965a',
    messagingSenderId: '224513566383',
    projectId: 'shopingmall-flutter-6ce8c',
    storageBucket: 'shopingmall-flutter-6ce8c.appspot.com',
    iosClientId: '224513566383-fhba2fnb7m688vo6j5d6sr740c31rbpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestshop',
  );
}
